### ISSUE TITLE
not working on iOS12

### ISSUE THREAD

**Issue by flyingbird** [evilpenguin/BoringSSLKeys#1]
I have changed offset for iOS12.
And it generates BoringSSLKey.keylog
But "wireshark -r capture.pcap -o tls:keylog_file:BoringSSLKey.keylog" can not Decrypting  iOS Traffic.

**Comment by evilpenguin** [comment]
What's inside the keylog file?

**Comment by flyingbird** [comment]
CLIENT_RANDOM e9a93b817c96f82bff341231417fe0020c5a6479d919ad2e7a49b0ce593ae29a d5d046b0b3dce9521f40194b6f5b9cd0cc4564d7ae894928cf50979b5ae66bca199bd00b637e186e06e1d7d8ef70dd15
many lines, but both are CLIENT_RANDOM 64-len 96-len string

**Comment by evilpenguin** [comment]
Do you not see: CLIENT_HANDSHAKE_TRAFFIC_SECRET, SERVER_HANDSHAKE_TRAFFIC_SECRET, CLIENT_TRAFFIC_SECRET_0, or SERVER_TRAFFIC_SECRET_0?

Those are required to decrypt.

**Comment by flyingbird** [comment]
no, only CLIENT_RANDOM

**Comment by evilpenguin** [comment]
Without those values a pcap can't be decrypted. Can you tell me the app you are capturing?

**Comment by flyingbird** [comment]
https://apps.apple.com/app/id379395415

**Comment by evilpenguin** [comment]
Can you try another application? Does another application work? 
Are you 100% certain this application has TLS traffic?

**Comment by flyingbird** [comment]
Yes, try another app. only CLIENT_RANDOM

**Comment by Brianning** [comment]
how to get the offset?
