### ISSUE TITLE
14.1 support

### ISSUE THREAD

**Issue by Wayne705** [evilpenguin/BoringSSLKeys#2]
Not issue but feature request to make this work on 14.1
Thank you for releasing so many awesome tools

**Comment by evilpenguin** [comment]
You just need to grab the offset from libboringssl on iOS 14 and update Tweak.x.

**Comment by evilpenguin** [comment]
Looks like the offset is `0x2B8` on iOS 14.

**Comment by evilpenguin** [comment]
Update this code: https://github.com/evilpenguin/BoringSSLKeys/blob/master/Tweak.xm#L62
with this offset: `0x2B8`
and then run `make package`

**Comment by evilpenguin** [comment]
`intptr_t **keylog_callback = (intptr_t **)(ctx_char + 0x2B8);`
